version: '3.6'
services:
  telegraf:
    image: telegraf:alpine
    volumes:
    - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - influxdb
      - elasticsearch
      - nginx
      - mongodb

    links:
      - influxdb
      - elasticsearch
      - nginx
      - mongodb

    ports:
    - '127.0.0.1:8125:8125/udp'
    user: telegraf

  socket-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: socket-proxy
    restart: always
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '127.0.0.1:2375:2375'
    environment:
      - LOG_LEVEL=debug # debug,info,notice,warning,err,crit,alert,emerg
      - CONTAINERS=1
      - INFO=1  
    
  influxdb:
    image: influxdb:1.8-alpine
    env_file: configuration.env
    ports:
      - '127.0.0.1:8086:8086'
    volumes:
      - ./:/imports
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:8.0.2
    depends_on:
      - influxdb
    env_file: configuration.env
    links:
      - influxdb
    ports:
      - '127.0.0.1:3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    environment:
      - discovery.type=single-node
    ports:
      - '9200:9200'
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    healthcheck:
      test: curl --silent --fail localhost:9200/_cluster/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    image: nginx:latest
    ports:
    - '127.0.0.1:80:80'
  
  mongodb:
    image: mongo:6.0.4
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=mydatabase
    ports:
      - '127.0.0.1:27017:27017'
    volumes:
      - mongodb_data:/data/db

  application:
    image: load-testing-demo
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch
      - mongodb
    environment:
      PORT: "8080"
      MONGO_HOST: "mongodb"
      MONGO_PORT: "27017"
      MONGO_DB: "mydatabase"
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "admin"
      ELASTIC_HOST: "elasticsearch"
      ELASTIC_PORT: "9200"
      TELEGRAF_PORT: "8125"

volumes:
  grafana_data: {}
  influxdb_data: {}
  elasticsearch_data:
  mongodb_data: {}
 
